package iotbay.controller;

import java.io.IOException;
import java.sql.Connection;
import java.util.Arrays;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import iotbay.helper.ProjectConstants;
import iotbay.helper.Validator;
import iotbay.model.User;
import iotbay.service.UserService;

public class RegisterController extends HttpServlet {
    // Using the POST method to handle user registration
    @Override
    public void doPost(HttpServletRequest request, HttpServletResponse response) {
        // Fetch session, fetch connection object from session and create a UserService instance
        HttpSession session = request.getSession();
        Connection connection = (Connection) session.getAttribute(ProjectConstants.SESSION_ATTRIBUTE_DBCONNECTION);
        UserService userService = new UserService(connection);

        // Get user details from request data
        String firstName = request.getParameter(ProjectConstants.REQUEST_ATTRIBUTE_USER_FIRST_NAME);
        String lastName = request.getParameter(ProjectConstants.REQUEST_ATTRIBUTE_USER_LAST_NAME);
        String email = request.getParameter(ProjectConstants.REQUEST_ATTRIBUTE_USER_EMAIL);
        String password = request.getParameter(ProjectConstants.REQUEST_ATTRIBUTE_USER_PASSWORD);

        /* 
        Create a new user object from the request data
        Note: The userId is set to -1 as it will be auto-generated by the database,
        and the hasAdminPermissions flag is set to false by default
        (System admins are unable to be created by users)
         */
        User newUser = new User(-1, firstName, lastName, email, password, false);

        try {
            if (userService.isEmailRegistered(email)) {
                // Send error message for already registered email
                session.setAttribute(ProjectConstants.SESSION_ATTRIBUTE_ERROR, "Email is already registered.");
                response.sendRedirect(ProjectConstants.REGISTER_PAGE);
                return;
            } else if (Validator.isEmpty(firstName) || Validator.isEmpty(lastName)) {
                // Send error message for missing names
                session.setAttribute(ProjectConstants.SESSION_ATTRIBUTE_ERROR, "First or last name is missing.");
                response.sendRedirect(ProjectConstants.REGISTER_PAGE);
                return;
            } else if (!Validator.validateEmail(email)) {
                // Send error message for invalid email
                session.setAttribute(ProjectConstants.SESSION_ATTRIBUTE_ERROR, "Invalid email.");
                response.sendRedirect(ProjectConstants.REGISTER_PAGE);
                return;
            } else if (!Validator.validatePassword(password)) {
                // Send error message for invalid password
                session.setAttribute(ProjectConstants.SESSION_ATTRIBUTE_ERROR, "Invalid password.");
                response.sendRedirect(ProjectConstants.REGISTER_PAGE);
                return;
            } else {
                handleRegistration(newUser, userService, session, response);
            }
        } catch (IOException e) {
            System.out.println("Could not send redirect from RegisterController");
            System.out.println(Arrays.toString(e.getStackTrace()));
        }
    }

    private void handleRegistration(User newUser, UserService userService, HttpSession session, HttpServletResponse response) {
        try {
            // Attempt to create the new user in the database, store it in session, and try to redirect to the home page
            userService.createUser(newUser);
            session.setAttribute(ProjectConstants.SESSION_ATTRIBUTE_USER, newUser);
            response.sendRedirect(ProjectConstants.HOME_PAGE);
            return;
        } catch (IOException e) {
            System.out.println("Could not send redirect from RegisterController");
            System.out.println(Arrays.toString(e.getStackTrace()));
        }
    }
}
